### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by KDL-in** [Ethan-Yan27/CSAPP-Labs#3]
请问能提供一下CSAPP官网的实验指导书和源文件吗，很想动手实践，苦于没有教育邮箱，下不了那些实验？
不要脸打扰实在抱歉

**Comment by Ethan-Yan27** [comment]
http://csapp.cs.cmu.edu/2e/labs.html 直接下载不需要账户的

**Comment by KDL-in** [comment]
3q



发自我的小米手机
在 Ethan-Yan27 <notifications@github.com>，2018年4月25日 上午9:39写道：

http://csapp.cs.cmu.edu/2e/labs.html 直接下载不需要账户的
